### ISSUE TITLE
User can delete users

### ISSUE THREAD

**Issue by TobCube** [koninklijke-collective/my_user_management#16]
Even if I restrict a user to very basic edit functionality, a user can still be deleted. Which doesnt make sense for me when the goal is to restrict editing functionality :-)

![user-admin_delete-user](https://cloud.githubusercontent.com/assets/7976366/15245803/1f22bd92-1909-11e6-8f97-acf24190679e.png)

Would be great if we can also prevent deleting.

**Comment by bmoex** [comment]
Hi @TobCube,

Thanks for reporting! Hope to get this done next week!

Kind regards,

Benjamin Serfhos

**Comment by TobCube** [comment]
Thank you! Just added a few more bugs or little feature changes that occurred while testing this great extension.

**Comment by bmoex** [comment]
A new custom permissions configuration will be added in the next release. This should be configured if they should be able to add/delete options for securing/override functionality;

![new user actions permissions configuration](https://cloud.githubusercontent.com/assets/2414665/16796772/9af20954-48e4-11e6-8a6e-912becb197dc.png)
