### ISSUE TITLE
Backend usergroup visible even without listing and modify

### ISSUE THREAD

**Issue by TobCube** [koninklijke-collective/my_user_management#19]
The restricted user has no access to backend usergroup table (no listing and no modification allowed). But its still possible to list the user-groups (user see only restricted groups but has an add group icon and can press save in detail view - without seeing any data for that group).

![switch](https://cloud.githubusercontent.com/assets/7976366/15246931/e4a3eefe-1910-11e6-9ec5-256a8120d3f5.png)

We only want to allow changing restricted groups for a user. Not maintaining users or groups at all.
![2016-05-13 13_48_46-test-tfl typo3 cms 7 6 5](https://cloud.githubusercontent.com/assets/7976366/15247000/7b36bc3e-1911-11e6-9ad5-b181c8aa9992.png)

![2016-05-13 13_48_24-test-tfl typo3 cms 7 6 5](https://cloud.githubusercontent.com/assets/7976366/15246998/76492162-1911-11e6-90dc-433672c736e3.png)

**Comment by bmoex** [comment]
Maybe a strange question, but whats the usecase? What do you want the maintenance user to edit in the group section then?

**Comment by TobCube** [comment]
The user should not be able to touch anything regarding a group. He just need to assign it to users.

use case:
Users log in via an external authentication which creates the users (disabled) when they login the first time (shibboleth - used for universities). Then there are siteadmins which should be able to enable those users and assign a limited set of groups for them. Nothing else should be allowed for those "site-admins". Fortunately we're currently building up just a one-role role-model so we can live with it. So at the moment they would be just able (if they are stupid enough) to remove their own role :-)
