### ISSUE TITLE
BE-Modul ist not compatible with fal_securedownload

### ISSUE THREAD

**Issue by johannessteu** [koninklijke-collective/my_user_management#23]
If you got https://github.com/beechit/fal_securedownload installed you can't use the be-modul for file mounts. The `StorageLocationViewHelper` requests a public url for a folder, but the extension only accepts files

![screen shot 2016-06-14 at 11 08 10](https://cloud.githubusercontent.com/assets/769789/16037403/9a966cf0-3220-11e6-8dfa-d6558ed9b877.png)

**Comment by bmoex** [comment]
Hi @johannessteu,

I have a feeling this was a bug of fal_securedownload. This is currently solved in https://github.com/beechit/fal_securedownload/commit/c72aa9b9d29d4925c50885a6ab4e2efd856623f6

Hope this answers your question.

Kind regard,

Benjamin Serfhos
