### ISSUE TITLE
Editing BE-Usergroup in v3.0.0 may crash backend

### ISSUE THREAD

**Issue by Ulfried** [koninklijke-collective/my_user_management#27]
Installing version 3.0.0 and setting the additional permissions in user group led for me :-( to the following _Uncaught TYPO3 Exception_:

> PHP Warning: strpos() expects parameter 1 to be string, array given in */typo3conf/ext/my_user_management/Classes/Hook/DataHandlerCheckModifyAccessListHook.php line 46

Disabling debug settings in install tool doesn't it make really better.

Apart from that: It's a nice extension solving my problem how editors can manage other users without being admin – thanks! (And version 2.3 is working yet :-) )

**Comment by bmoex** [comment]
Thanks for reporting! :-)
