### ISSUE TITLE
Information icon in overview shows blank/white page

### ISSUE THREAD

**Issue by TobCube** [koninklijke-collective/my_user_management#31]
![be-user-overview](https://cloud.githubusercontent.com/assets/7976366/18381820/5c7c6b66-767e-11e6-822d-d781baf85b6e.png)
When clicking on the information icon in overview, theres a blank/white page and no information are shown. The compare functionality is working properly.

Access right should be available:
![tables-listing-be-group](https://cloud.githubusercontent.com/assets/7976366/18381741/fe9eb3aa-767d-11e6-95bf-3f06c20bdf3a.png)

**Comment by agendartobias** [comment]
Hello in TYPO3 8.7.8 (module version 3.3.4) i have the same problem. Admin user can see information, other users cant. Can you help me?
