### ISSUE TITLE
Switching to different user-Right has no effect

### ISSUE THREAD

**Issue by TobCube** [koninklijke-collective/my_user_management#35]
When checking the access right "Switching to different user", the user switch does not appear for the user (icon in user overview).

![image](https://cloud.githubusercontent.com/assets/7976366/22017357/625721ec-dcaa-11e6-89f2-8e56c780de9b.png)

![image](https://cloud.githubusercontent.com/assets/7976366/22017392/7a45f74c-dcaa-11e6-82b2-4a8969698258.png)

**Comment by bmoex** [comment]
I think in the screenshot you are already switch to the user to see the workflow. :-)
This was a security risk - https://forge.typo3.org/issues/73797


Needed to dig into the core to find this though :D

**Comment by TobCube** [comment]
Thanks yes indeed! :) Works like a charm with a "hard" login.
