### ISSUE TITLE
TYPO3 4.5 compatible?

### ISSUE THREAD

**Issue by rewebit** [koninklijke-collective/my_user_management#42]
Hello,
Yup, know that someone (s) is/are cringing with this question... Any chance the earlier versions were compatible with TYPO3 4.5? 

version 1.1.0 Perhaps?...

https://extensions.typo3.org/extension/my_user_management/

**Comment by bmoex** [comment]
Hi @rewebit,

The first release was for TYPO3 6.2. So no, sorry :-(
