### ISSUE TITLE
Tab Access not visible

### ISSUE THREAD

**Issue by DerVolli** [koninklijke-collective/my_user_management#43]
Even if I grant starttime and endtime for a usergroup which should be able to use the backend user administration the tab "Access" is not showing for users who have this group. The rest seemed to work.

We are still using typo3 6.2, not yet tested in typo3 8 (which we are moving to this year, but a solution for 6.2 would be very appreciated!)

**Comment by itzonban** [comment]
Hi @DerVolli,

I have the same issue with TYPO3 8. It looks like it's hard-coded in Configuration/TCA/Overrides/be_users.php:

```
// Make all fields to exclude for users
foreach ($GLOBALS['TCA']['be_users']['columns'] as $key => &$configuration) {
    $configuration['exclude'] = 1;
    switch ($key) {
        // Ignore certain fields
        case 'admin':
        case 'starttime':
        case 'endtime':
            $configuration['displayCond'] = 'HIDE_FOR_NON_ADMINS';
            break;
    }
}
```
Is there a reason why starttime and endtime are listed here? We use "webmaster" groups, which should be able to set start/endtime. And even the 'admin' field shouldn't be neccessary, just don't grant it to the user/group...

Best regards
Daniel
