### ISSUE TITLE
Retain compatibility with TYPO3 v8

### ISSUE THREAD

**Issue by stucki** [koninklijke-collective/my_user_management#47]
After the recent commits in master, this extension will no longer work with TYPO3 v8.

There are 3.3.x tags (5 tags pointing to the same commit), but they don't include the latest fix: https://github.com/koninklijke-collective/my_user_management/pull/44

My suggestion is to create a new tag `3.3.5` which points to https://github.com/koninklijke-collective/my_user_management/commit/423312cb46f576b0d29d8e7e6972b0ca2fb0b90b.

**Comment by bmoex** [comment]
Hi @stucki,

I tagged the repository in Git with the 3.3.5 tag. I wont release this on TER. Sorry if this wont help out.

**Comment by stucki** [comment]
Thank you!
