### ISSUE TITLE
Extension fails because of breaking change (be_groups.hide_in_list)

### ISSUE THREAD

**Issue by instruccionesaldorso** [koninklijke-collective/my_user_management#48]
When installing the latest version on master compatible with 9.5, the extension breaks the instance because of this breaking change:
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.0/Breaking-81534-DatabaseFieldBe_groupshide_in_listsDropped.html

Code inside the extension still uses such field in be_groups table.

**Comment by bmoex** [comment]
Thanks for reporting!

**Comment by instruccionesaldorso** [comment]
Thanks!
