### ISSUE TITLE
An other be_groups.hideInList occurrence

### ISSUE THREAD

**Issue by AMartinNo1** [koninklijke-collective/my_user_management#49]
I noticed that there's one more occurrence of `be_groups.hideInList`
> https://github.com/koninklijke-collective/my_user_management/blob/master/Classes/Domain/Repository/BackendUserGroupRepository.php#L25

Related issue: #48

**Comment by moe2k** [comment]
I can reproduce this Issue on TYPO3 9.5.16 and my_user_management 4.0.4. Please consider merging the pull request, it fixes this bug.
https://github.com/koninklijke-collective/my_user_management/pull/50

**Comment by AMartinNo1** [comment]
Due to the merged PR I will close this.
