### ISSUE TITLE
wrong version on TER

### ISSUE THREAD

**Issue by junfan59** [koninklijke-collective/my_user_management#56]
The extension 4.0.0 on TER broke TYPO3 9 existing install with this error : 
KoninklijkeCollective\MyUserManagement\Domain\DataTransferObject\BackendUserActionPermission not found

It will be nice to update the TER...?
Tanks

**Comment by bmoex** [comment]
The extension was already available on packagist. I just reuploaded 5.0 and 7.0 in TER
