### ISSUE TITLE
Filemont error with private File Storage

### ISSUE THREAD

**Issue by julebbb** [koninklijke-collective/my_user_management#58]
Dear,
I use my_user_management extension on a TYPO3 9.5 which use private "File Storage" with some permissions created with fal_securedownload).
When I click on the "Backend Management File Mounts" module I got this error.

![Capture du 2021-01-21 09-59-23](https://user-images.githubusercontent.com/39909899/105485623-7c556180-5cad-11eb-99eb-fdff5b52de91.png)

I think because $folder->getPublicUrl(); return null.

On TYPO3 8.7 my_user_management return $storage->getUid() . ':' . $location;

So on TYPO3 9 I added a condition if $folder->getPublicUrl() === null.

```
 46: if ($folder === null || $folder->getPublicUrl() === null) {
 47:          return $storage->getUid() . ':' . $location;
 48:  } else {
 49:           return $folder->getPublicUrl();
 50: }
```

Is it ok to do that or there is some security problems related to this modification ?

Could you please add a make to solve this issue ?

Thank you so much

**Comment by freshworkx** [comment]
I can confirm this behavior for TYPO3 9.5.24, my_user_management 4.1.0 combined with fal_securedownload 2.2.1
