### ISSUE TITLE
Wrong typo3 requirements in ext_emconf.php

### ISSUE THREAD

**Issue by sterborg** [koninklijke-collective/my_user_management#59]
Version 5.0.0 has wrong typo3 requirements in ext_emconf.php:

'typo3' => '9.5.0-9.5.99'

This should at least include 10.4.

**Comment by vte-udg** [comment]
I second that :) You can install the extension but you have to turn off the dependency checks which you don't really want to do...

**Comment by bmoex** [comment]
Version 6 & 7 now have the right requirements in ext_emconf.php
