### ISSUE TITLE
Error in login history module in TYPO3 v10

### ISSUE THREAD

**Issue by sterborg** [koninklijke-collective/my_user_management#60]
In **TYPO3 10.4.16** with **my_user_management 5.0.0** I get an error in login history module:
"Call to undefined method Doctrine\DBAL\Driver\Mysqli\MysqliStatement::fetchAllAssociative()"
in .../public/typo3conf/ext/my_user_management/Classes/Domain/Repository/LoginHistoryRepository.php line 46

Tested with **doctrine/dbal 2.10.4**

**Comment by bmoex** [comment]
Should be fixed since [6.0.0](https://github.com/koninklijke-collective/my_user_management/tree/6.0.0)
