### ISSUE TITLE
InvalidActionNameException when accessing

### ISSUE THREAD

**Issue by vte-udg** [koninklijke-collective/my_user_management#61]
# Bug Report

## Prerequisites

* [ ] Did you reproduce the problem on TYPO3 core master?
* [x] Did you reproduce the problem on TYPO3 v10.4 LTS?
* [ ] Did you reproduce the problem on TYPO3 v9.5 LTS?

## Description

When I try to access the detail-view of permissions a user has (this is new to TYPO3 in V10) via Backend Management > User Admin an exception is thrown:
`
The action "show" (controller "KoninklijkeCollective\MyUserManagement\Controller\BackendUserController") is not allowed by this plugin / module. Please check TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php / TYPO3\CMS\Extbase\Utility\ExtensionUtility::configureModule() in your ext_tables.php. 
`

## Steps to Reproduce

1. Go to Backend Management > User Admin
2. Click on the "Show details" icon next to a backend-user
![mum-issue1](https://user-images.githubusercontent.com/65022159/126355615-e0cf5903-d9a6-42e9-b324-109e69e42ed4.png)

**Expected behavior:**
I can access the detail-view of the backend-user that lists all his permissions.
![mum-issue2](https://user-images.githubusercontent.com/65022159/126356115-87902222-cdce-4b2a-9698-3405f443ff16.png)
Ideally though, this view / this button should not exist, at least not for regular editors as they should not be able to see all permission in detail.

**Actual behavior:** 
TYPO3\CMS\Extbase\Mvc\Exception\InvalidActionNameException
`
The action "show" (controller "KoninklijkeCollective\MyUserManagement\Controller\BackendUserController") is not allowed by this plugin / module. Please check TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php / TYPO3\CMS\Extbase\Utility\ExtensionUtility::configureModule() in your ext_tables.php. 
`

## Versions
5.0

**Comment by bmoex** [comment]
Show is added in 7.0.0
