### ISSUE TITLE
Update for typo3 11

### ISSUE THREAD

**Issue by drogu02** [koninklijke-collective/my_user_management#64]
Hi!

Is support for TYPO3 11.5 planned? This would be great! That extension is a must for me!

Tx, Guillaume

**Comment by susannemoog** [comment]
I gave it a shot at https://github.com/koninklijke-collective/my_user_management/pull/65

**Comment by bmoex** [comment]
I verified the code and did some refactoring cause fallback to v9 was not yet supported anymore. 
See version [7.0.0](https://github.com/koninklijke-collective/my_user_management/tree/7.0.0) for release & composer dependencies. Thanks @susannemoog for the input!
