### ISSUE TITLE
Git-Tag for typo3 v10 missing (breaks composer use)

### ISSUE THREAD

**Issue by wapp-its** [koninklijke-collective/my_user_management#66]
# Bug Report

## Description

Unfortunately there is no tag or branch for typo3 v10. As the master branch now got typo3 v11 compatibility, this breaks typo3 v10 composer installations which uses master (because of a lack of better options).
 
Can you please add a tag (for example 6.0) for the latest v10 compatible commit on [TYPO3 10 compatibility](https://github.com/koninklijke-collective/my_user_management/commit/4c95f82630953e7ebef3c9d39e9794fdd8f14d77)?

**Comment by bmoex** [comment]
Tag 6.0.0 is now available!
