### ISSUE TITLE
A non admin user can't simulate another backend user in typo3 11

### ISSUE THREAD

**Issue by drogu02** [koninklijke-collective/my_user_management#67]
A non admin user can't simulate another backen user in typo3 v11

[Description of the bug]

## Steps to Reproduce

1. Log with a non-admin user who have access to create/modify backend users
2. Go to Backend users in left menu
3. You can't see the arrow to simulate another user. 

That option is not possible anymore for a non-admin user. It was possible in typo3 v8 with the extension my_user_management

Typo3 11.5.16
my_user_management  7.0.0

**Comment by mz-aimcom** [comment]
Same here. I can confirm the issue.

**Comment by mz-aimcom** [comment]
@bmoex @jp1987 I just created a pull request #68 that should fix this issue.

@drogu02 Maybe you can try it out if it also works for you.

**Comment by drogu02** [comment]
Yes it work for me now! 

The only thing that was working earlier that is not working with that Fix is : 

Situation 1 : Log with a user with switch access  **->**  Switch to another user  **(Working well)**
Situation 2 : Log with an admin  **->**  Swith to a user with switch access  **->**  Switch to another user  **(Not working - Error appear : Switching to user went wrong)**

**Comment by mz-aimcom** [comment]
@drogu02 Yes, switching when already switched is not allowed. I'm not sure if that would be a good idea. E.g. "User A" switches to "User B" and then switches to "User A". I think it's getting complicated, then.🙈

**Comment by drogu02** [comment]
@mz-aimcom yes I understand! :) Tx for your help!
